# Every path is inside an isolated build directory; no recursive deletion.
file(MAKE_DIRECTORY "${OUTPUT_ROOT}")
file(WRITE "${OUTPUT_ROOT}/blocked-file" "not a directory")
execute_process(COMMAND "${TOOL}" "${OUTPUT_ROOT}/blocked-file" RESULT_VARIABLE result)
if(result EQUAL 0)
  message(FATAL_ERROR "Qualification accepted a file as its output directory")
endif()
file(MAKE_DIRECTORY "${OUTPUT_ROOT}/blocked-stream/bbd_phase_semantics.csv")
execute_process(COMMAND "${TOOL}" "${OUTPUT_ROOT}/blocked-stream" RESULT_VARIABLE result)
if(result EQUAL 0)
  message(FATAL_ERROR "Qualification accepted an unopenable artifact")
endif()
if(UNIX AND EXISTS "/dev/full")
  file(MAKE_DIRECTORY "${OUTPUT_ROOT}/failed-write")
  file(CREATE_LINK "/dev/full" "${OUTPUT_ROOT}/failed-write/README.txt" SYMBOLIC)
  execute_process(COMMAND "${TOOL}" "${OUTPUT_ROOT}/failed-write" RESULT_VARIABLE result)
  if(result EQUAL 0)
    message(FATAL_ERROR "Qualification accepted a failed artifact write/flush")
  endif()
endif()
